name: Deploy ENP to GitHub Pages

on:
  push:
    branches:
      - main   # whenever you push to main, redeploy

permissions:
  contents: write   # allow GitHub Actions bot to push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages       # branch where Pages is served
          publish_dir: ./dist            # ✅ publish build output
          destination_dir: .             # ✅ flatten so /taskpane.html is at root
